# Generated by Django 3.1 on 2020-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201021_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
