# Generated by Django 3.1 on 2020-10-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201023_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='starting_bid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_price',
        ),
    ]
